id = "rsx"
name = "RSX"
description = "RSX language support for Zed - A full-stack web framework combining Rust, TypeScript, Handlebars templates, and SCSS"
version = "0.2.0"
schema_version = 1
authors = ["michael <michaelbguo@tencent.com>"]
repository = "https://github.com/guobin211/rsx-zed"

[grammars.rsx]
repository = "https://github.com/guobin211/tree-sitter-rsx"
commit = "f100e5eab7836bd26fd1e11da288ff2181de327d"
