id = "rsx"
name = "RSX"
description = "RSX language support for Zed - A full-stack web framework combining Rust, TypeScript, Handlebars templates, and SCSS"
version = "0.2.0"
schema_version = 1
authors = ["michael <michaelbguo@tencent.com>"]
repository = "https://github.com/guobin211/tree-sitter-rsx"

[grammars.rsx]
repository = "https://github.com/guobin211/tree-sitter-rsx"
rev = "7f90e44c8566a5242e659a1cd186e5a2825645fe"
