id = "rsx"
name = "RSX"
description = "RSX language support for Zed - A full-stack web framework combining Rust, TypeScript, Handlebars templates, and SCSS"
version = "0.2.0"
schema_version = 1
authors = ["michael <michaelbguo@tencent.com>"]
repository = "https://github.com/guobin211/rsx-zed"

[grammars.rsx]
repository = "https://github.com/guobin211/tree-sitter-rsx"
commit = "941e90732b66d27b7423cb7e30f19d88789de886"
