id = "rsx"
name = "RSX"
description = "RSX language support for Zed - A full-stack web framework combining Rust, TypeScript, Handlebars templates, and SCSS"
version = "0.2.0"
schema_version = 1
authors = ["michael <michaelbguo@tencent.com>"]
repository = "https://github.com/guobin211/rsx-zed"

[grammars.rsx]
repository = "https://github.com/guobin211/tree-sitter-rsx"
commit = "0a919b40ebf094f4e2e9ff85992e94e03eb13322"

[language_servers.rsx-language-server]
name = "RSX Language Server"
languages = ["rsx"]

[language_servers.rsx-language-server.language_ids]
rsx = "rsx"
